---
- name: Unmount server data disk
  shell: umount /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}
  become: true

- name: Remove mount point
  file:
    path: /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}
    state: absent
  become: true

- name: Detach server data disk
  ec2_vol:
    id: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.data.ebs.vol_id', region='ap-southeast-1') }}"
    instance: None



