---

- name: Detach Network Interface
  ec2_eni:
    instance_id: "{{ ansible_ec2_instance_id }}"
    eni_id: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.eni_id', region='ap-southeast-1') }}"
    attached: no