---

- name: Start the CloudWatch Agent
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:{{ lookup('env', 'MC_SERVER_NAME') }}.cwagent -s
  become: true