---

- name: Unmount map data disk
  shell: umount /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}_map
  become: true

- name: Remove mount point
  file:
    path: /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}_map
    owner: mc_server
    group: mc
    mode: '6775'
    state: absent
  become: true

- name: Detach map data disk (EBS)
  ec2_vol:
    id: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.dynmap.ebs.vol_id', region='ap-southeast-1') }}"
    instance: None
  when: not use_efs
