---

- name: Copy termination listener
  copy:
    src: ../files/termination_listener.py
    dest: /home/ec2-user

- name: Start termination listener
  script:
    cmd: ./start_termination_listener.sh
    chdir: /home/ec2-user
