---
- hosts: all
  vars:
    use_efs: "{{ lookup('env', 'MC_USE_EFS') | bool or false }}"
  pre_tasks:
    - name: Get facts
      ec2_metadata_facts:
      tags: always

  roles:
    - {role: setenv, tags: env}
    - {role: cwagent, tags: env}
    - {role: mount_server_disk, tags: disk}
    - {role: mount_map_disk, tags: disk}
    - {role: terminationlistener, tags: server}
    - {role: minecraft, tags: server}
    - {role: eni, tags: network}