---

- name: Attach server data disk
  ec2_vol:
    id: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.data.ebs.vol_id', region='ap-southeast-1') }}"
    instance: "{{ ansible_ec2_instance_id }}"
    device_name: /dev/sdf
    state: present

- name: Wait for volume to be available
  shell: file /dev/sdf -b | grep -q 'symbolic link'
  register: result
  until: result.rc == 0
  retries: 10
  delay: 1
  ignore_errors: yes

- name: Create mount point
  file:
    path: /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}
    state: directory
    owner: mc_server
    group: mc
    mode: '6775'
  become: true

- name: Mount server data disk
  shell: mount /dev/sdf /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}
  become: true

#- debug:
#    msg: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.data.ebs.vol_id', region='ap-southeast-1') }}"
#
#- name: Hold up
#  pause:
#    seconds: 10