---

- name: Start the server
  shell:
    chdir: /var/mc/{{ lookup('env', 'MC_SERVER_NAME') }}
    cmd: |
      tmux -S tmux.sock new-session -s server -d
      tmux -S tmux.sock send-keys -t server "./LaunchServer.sh" ENTER
  become: yes
  become_user: mc_server

- name: Wait for server to finish launching
  wait_for:
    host: 0.0.0.0
    port: "{{ lookup('aws_ssm', lookup('env', 'MC_SERVER_NAME') ~ '.ansible.wait_for_port', region='ap-southeast-1') }}"
    delay: 10